// <auto-generated />
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(databaseContext))]
    [Migration("20220127003117_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilmDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("FilmId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            Category = "Action/Adventure",
                            Edited = false,
                            FilmDirector = "George Lucas",
                            FilmRating = "PG",
                            FilmTitle = "Indiana Jones and the Raiders of the Lost Ark",
                            FilmYear = 1981,
                            LentTo = "",
                            Notes = ""
                        },
                        new
                        {
                            FilmId = 2,
                            Category = "Action/Adventure",
                            Edited = false,
                            FilmDirector = "Gore Verbinski",
                            FilmRating = "PG-13",
                            FilmTitle = "Pirates of the Caribbean: The Curse of the Black Pearl",
                            FilmYear = 2003,
                            LentTo = "",
                            Notes = ""
                        },
                        new
                        {
                            FilmId = 3,
                            Category = "Adventure/Romance",
                            Edited = false,
                            FilmDirector = "Kevin Reynolds",
                            FilmRating = "PG-13",
                            FilmTitle = "The Count of Monte Cristo",
                            FilmYear = 2002,
                            LentTo = "",
                            Notes = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
